const NoRepeat = require("no-repeat");

module.exports = {
  opening: new NoRepeat([
    "It's been great talking to you, but",
    "I gotta run,",
    "Look over there!",
    "Sorry to do this, but",
    "Sorry to interupt you, but",
    "Give your family my best, because",
    "I wish I could talk, but",
    "I just got a text:",
    "Didn't you hear?",
    "You might want to sit down.",
    "Ey mate, i got to yeet yote out of this boat,",
    "Wait, is that… yeah!",
    "You're not going to believe this, but",
    "What in tarnation?!",
    "Good luck with that, but",
    "I've gotta make like a tree and leaf.",
    "Uhuh. yeah. that's really interesting. Hey listen,",
    "Well would ya look at that.",
    "Did you see this post on the discord? It says that",
    "Fun fact:"
  ]),
  person: new NoRepeat([
    "my dog",
    "#youth",
    "my mother",
    "Franziska",
    "Jane",
    "Martha Stewart",
    "Lara Croft",
    "GLaDOS",
    "Joe",
    "Tom",
    "Billy",
    "Fred",
    "Noah",
    "Steve",
    "LDSG Ghost",
    "Santana",
    "Gandalf the Grey",
    "The Legend 27",
    "Chuck Norris",
    "Ryn",
    "Cave Johnson",
    "Huddy",
    "Zorp, Ruler of the Nine Cosmo's",
    "a local boyband",
    "a group of door-to-door salesmen",
    "my high school basketball team",
    "a member of the royal guard",
    "a mall santa",
    "a snail",
    "my Harry Potter cardboard cutout",
    "my imaginary girlfriend",
    "<@authorname>",
    "my car",
    "a hive of bees",
    "my friend's fridge",
    "that one guy from that one show",
    "a sentient fish",
    "twitch chat",
    "a Florida man",
    "the Immortal God-Empress",
    "a sentient bottle of lotion",
    "half of my D&D group",
    "a black hole",
    "an alien",
    "JOHN CENA",
    "a member of Freshbeast",
    "a member of Starcamp",
    "a member of Brightbeam",
    "the elusive and terrifying slothmare",
    "my buttermelon sandwich",
    "Jerry's pet handicorn",
  ]),
  event: new NoRepeat([
    "is invading <@channel>",
    "just broke into my house",
    "just crashed my car",
    "just came back to life",
    "just fell in the neighbor's pool",
    "is splitting an atom in my backyard",
    "just got assaulted by the mailman",
    "is trying to figure out how to navigate their college website",
    "just lost their ankles",
    "has been on twitter for too long",
    "just failed a captcha for the 5th time",
    "is doing a handstand",
    "just stared breakdancing",
    "died of dysentery",
    "just got me that new game I've been wanting to play",
    "just fired IndigoWolf",
    "is trying to use PHAROS to print",
    "is trying to optimize Surge Alloy production",
    "is doing a handstand on my dog",
    "just texted the IRS on accident",
    "just ate my homework",
    "downloaded Destiny 2",
    "is trying to summon the !beandemon",
    "just broke through my trampoline",
    "is trying to frame me for a crime they committed",
    "has declared that all our base belong to them",
    "is trying to eat my pizza rolls",
    "is trying to convince Tod Howard to port Skyrim again",
    "has a sword and is running here at mach 2",
    "is putting too much flour into the cake",
    "has been perfecting their taco recipe and I gotta try it",
    "grabbed a flamethrower and set <@channel> ablaze",
    "is about to jump-scare the mailman!",
    "just jumped the fence and is crouch jumping into the sunset",
    "is going to be late for dance class unless I give them a ride",
    "is hovering their finger over the \"purge members\" button",
    "has fallen into the river in Lego City",
    "wants to bike 12 hours to the beach and I don't want to go with them",
    "is trying to tag me",
    "is trying to recruit me",
    "has been trying to contact me about my car's extended warranty"
  ])
};